# ██╗    ██╗██╗  ██╗ ██████╗ ████████╗██╗  ██╗
# ██║    ██║██║ ██╔╝██╔═══██╗╚══██╔══╝██║  ██║
# ██║ █╗ ██║█████╔╝ ██║   ██║   ██║   ███████║
# ██║███╗██║██╔═██╗ ██║   ██║   ██║   ██╔══██║
# ╚███╔███╔╝██║  ██╗╚██████╔╝   ██║   ██║  ██║
#  ╚══╝╚══╝ ╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝
#
# Plugin desarrollado por wwishh
# Version: 1.0.3
# Discord: wwishh
# GitHub: github.com/wwishhdev

# Configuración general
settings:
  default-capture-time: 300 # Tiempo por defecto en segundos (5 minutos)
  announcement-interval: 30 # Intervalo en segundos para anunciar el tiempo restante
  broadcast-capture: true # Si se debe anunciar cuando alguien captura/pierde el control
  chest-duration: 60 # Duración en segundos que permanece el cofre de recompensas

# Mensajes del plugin
messages:
  prefix: "&r"
  no-permission: "&cNo tienes permiso para usar este comando!"
  player-only: "&cEste comando solo puede ser ejecutado por jugadores!"

  # Mensajes de ayuda
  help-title: "&6Comandos de wKoth:"
  help-create: "&e/koth create <nombre> - Obtén el stick para seleccionar la zona"
  help-set: "&e/koth set - Establece el KoTH en la zona seleccionada"
  help-list: "&e/koth list - Muestra la lista de KoTHs"
  help-delete: "&e/koth delete <nombre> - Elimina un KoTH"
  help-start: "&e/koth start <nombre> - Inicia un KoTH"
  help-stop: "&e/koth stop <nombre> - Detiene un KoTH"
  help-reload: "&e/koth reload - Recarga la configuración"

  # Mensajes del sistema de captura
  koth-started: |
    &6=========================
    &e¡El KoTH '%koth%' ha comenzado!
    &eTiempo de captura: %time%
    &6=========================
  koth-ended: |
    &6=========================
    &c¡El KoTH '%koth%' ha terminado!
    &6=========================
  koth-winner: |
    &6=========================
    &a¡%player% ha ganado el KoTH '%koth%'!
    &6=========================
  koth-time-left: |
    &6=========================
    &eTiempo restante del KoTH '%koth%': %time%
    &6=========================
  player-capturing: |
    &6=========================
    &e¡%player% está capturando el KoTH '%koth%'!
    &6=========================
  player-lost-control: |
    &6=========================
    &c¡%player% ha perdido el control del KoTH '%koth%'!
    &6=========================
  position-selected-1: "&aHas seleccionado la primera posición para el KoTH!"
  position-selected-2: "&aHas seleccionado la segunda posición para el KoTH!"

  # Mensajes de creación
  create-usage: "&cUso correcto: /koth create <nombre>"
  koth-already-exists: "&cYa existe un KoTH con ese nombre!"
  selection-tool-given: "&a¡Has recibido el stick de selección! Haz click derecho para seleccionar la primera posición y click izquierdo para la segunda."
  must-create-first: "&c¡Primero debes crear un KoTH con /koth create <nombre>!"
  must-select-positions: "&c¡Primero debes seleccionar ambas posiciones!"
  koth-created: "&a¡KoTH '%koth%' creado exitosamente!"

  # Mensajes de lista
  no-koths: "&eNo hay KoTHs creados."
  koth-list-header: "&6Lista de KoTHs:"
  koth-list-entry: "&e- %koth% (Mundo: %world%, Pos1: %pos1%, Pos2: %pos2%)"

  # Mensajes de inicio/parada
  start-usage: "&cUso correcto: /koth start <nombre>"
  stop-usage: "&cUso correcto: /koth stop <nombre>"
  koth-not-exist: "&cNo existe un KoTH con ese nombre!"
  koth-already-active: "&c¡Este KoTH ya está activo!"
  koth-not-active: "&c¡Este KoTH no está activo!"
  koth-started-success: "&a¡KoTH '%koth%' iniciado!"
  koth-stopped-success: "&a¡KoTH '%koth%' detenido!"

  # Mensajes de eliminación
  delete-usage: "&cUso correcto: /koth delete <nombre>"
  koth-deleted: "&a¡KoTH '%koth%' eliminado exitosamente!"

  # Mensaje de recarga
  reload-success: "&a¡Configuración recargada exitosamente!"

  # Mensajes del sistema de cofres
  chest-reward-spawned: "&a¡Ha aparecido un cofre de recompensas en la posición designada! Tienes %time% segundos para reclamarlo."
  chest-only-winner: "&cEste cofre solo puede ser abierto por el ganador del KoTH."
  chest-location-set: "&aUbicación del cofre establecida correctamente para el KoTH '%koth%'."
  chest-loot-saved: "&aLoot guardado correctamente para el KoTH '%koth%'."
  chest-no-location: "&cPrimero debes establecer una ubicación para el cofre con /koth set-chest."
  chest-toggle-command: "&aAhora se usarán recompensas por COMANDOS para el KoTH '%koth%'."
  chest-toggle-chest: "&aAhora se usarán recompensas por COFRE para el KoTH '%koth%'."

# Configuración específica de cada KoTH
koths: