# ██╗    ██╗██╗  ██╗ ██████╗ ████████╗██╗  ██╗
# ██║    ██║██║ ██╔╝██╔═══██╗╚══██╔══╝██║  ██║
# ██║ █╗ ██║█████╔╝ ██║   ██║   ██║   ███████║
# ██║███╗██║██╔═██╗ ██║   ██║   ██║   ██╔══██║
# ╚███╔███╔╝██║  ██╗╚██████╔╝   ██║   ██║  ██║
#  ╚══╝╚══╝ ╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝
#
# Plugin desarrollado por wwishh
# Version: 1.0.0
# Discord: wwishh
# GitHub: github.com/wwishh777

############################################################
# +------------------------------------------------------+ #
# |                   Configuración Global               | #
# +------------------------------------------------------+ #
############################################################

settings:
  # Tiempo de espera entre KoTHs (en segundos)
  # Default: 3600 (1 hora)
  cooldown: 3600

  # Intervalo de mensajes de broadcast (en segundos)
  # Default: 60 (1 minuto)
  broadcast-interval: 60

############################################################
# +------------------------------------------------------+ #
# |                      Mensajes                        | #
# +------------------------------------------------------+ #
############################################################

messages:
  prefix: "&8[&6KoTH&8] "

  # Mensajes de eventos
  koth-start: "&aEl KoTH &6%koth% &aha comenzado!"
  koth-end: "&cEl KoTH &6%koth% &cha terminado!"
  koth-captured: "&6%player% &eha capturado el KoTH &6%koth%&e!"
  koth-control: "&e%player% &7está controlando el KoTH &6%koth%&7! &8(&f%time%&8)"

  # Mensajes de administración
  no-permission: "&c✘ &7No tienes permiso para usar este comando!"
  pos1-set: "&a✔ &7Pos1 establecida correctamente para el KoTH &6%koth%&7!"
  pos2-set: "&a✔ &7Pos2 establecida correctamente para el KoTH &6%koth%&7!"
  config-reloaded: "&a✔ &7La configuración ha sido recargada correctamente!"

  # Mensajes de gestión de KoTHs
  koth-created: "&a✔ &7KoTH &6%koth% &7creado correctamente!"
  koth-deleted: "&c✘ &7KoTH &6%koth% &7eliminado correctamente!"
  koth-not-found: "&c✘ &7El KoTH &6%koth% &7no existe!"
  koth-already-exists: "&c✘ &7El KoTH &6%koth% &7ya existe!"
  koth-list: "&6KoTHs disponibles: &f%koths%"

############################################################
# +------------------------------------------------------+ #
# |                  KoTHs Configurados                  | #
# +------------------------------------------------------+ #
############################################################

koths:
  # Ejemplo de KoTH
  example:
    # Nombre mostrado del KoTH
    name: "Example"

    # Duración en segundos
    # Default: 900 (15 minutos)
    duration: 900

    # Posiciones del KoTH (se establecen con comandos)
    pos1: null
    pos2: null

    # Recompensas al ganar
    rewards:
      commands:
        - "give %player% diamond 64"
        - "eco give %player% 10000"
        - "broadcast &a¡%player% ha ganado un kit de diamante por ganar el KoTH!"

############################################################
#                                                          #
#                    Fin de la configuración               #
#                                                          #
# Para más información o soporte:                          #
# - Discord: wwishh                                        #
# - GitHub: github.com/wwishh777                           #
#                                                          #
############################################################