# ██╗    ██╗██╗  ██╗ ██████╗ ████████╗██╗  ██╗
# ██║    ██║██║ ██╔╝██╔═══██╗╚══██╔══╝██║  ██║
# ██║ █╗ ██║█████╔╝ ██║   ██║   ██║   ███████║
# ██║███╗██║██╔═██╗ ██║   ██║   ██║   ██╔══██║
# ╚███╔███╔╝██║  ██╗╚██████╔╝   ██║   ██║  ██║
#  ╚══╝╚══╝ ╚═╝  ╚═╝ ╚═════╝    ╚═╝   ╚═╝  ╚═╝
#
# Plugin desarrollado por wwishh
# Version: 1.0.0
# Discord: wwishh
# GitHub: github.com/wwishh777