name: wKoth
version: 1.0.0
main: com.wish.wKoth.wKoth
description: Plugin de KoTH con soporte para múltiples arenas
commands:
  koth:
    description: Comando principal del plugin wKoth
    usage: /koth <subcomando>
permissions:
  wkoth.admin:
    description: Permite usar todos los comandos administrativos del KoTH
    default: op