name: wKoth
version: 1.0.8
main: com.wish.wKoth.wKoth
author: wwishh
description: Sistema de KoTH avanzado con soporte para múltiples arenas
website: https://github.com/wwishhdev
softdepend: [PlaceholderAPI]

commands:
  koth:
    description: Comando principal del plugin wKoth
    usage: /<command> [create|set|list|delete|start|stop|reload|set-capture-time|set-duration|set-commands|list-commands|remove-command|set-schedule|set-chest|set-loot|view-loot]

permissions:
  wkoth.admin:
    description: Permite usar todos los comandos del plugin
    default: op
    children:
      wkoth.create: true
      wkoth.delete: true
      wkoth.start: true
      wkoth.stop: true
      wkoth.reload: true
      wkoth.list: true
      wkoth.command: true
      wkoth.chest: true

  wkoth.create:
    description: Permite crear y editar KoTHs
    default: op

  wkoth.delete:
    description: Permite eliminar KoTHs
    default: op

  wkoth.start:
    description: Permite iniciar un KoTH
    default: op

  wkoth.stop:
    description: Permite detener un KoTH
    default: op

  wkoth.reload:
    description: Permite recargar la configuración del plugin
    default: op

  wkoth.list:
    description: Permite ver la lista de KoTHs
    default: op

  wkoth.command:
    description: Permite gestionar comandos de recompensa
    default: op

  wkoth.chest:
    description: Permite gestionar cofres de recompensa
    default: op
    children:
      wkoth.chest.set: true
      wkoth.chest.loot: true

  wkoth.chest.set:
    description: Permite establecer la ubicación del cofre de recompensas
    default: op

  wkoth.chest.loot:
    description: Permite configurar y ver el loot de los cofres
    default: op

  wkoth.viewloot:
    description: Permite ver el loot de un KoTH (solo lectura)
    default: true