name: wKoth
version: 1.0.2
main: com.wish.wKoth.wKoth
author: wwishh
description: Sistema de KoTH avanzado con soporte para múltiples arenas

commands:
  koth:
    description: Comando principal del plugin wKoth
    usage: /<command> [create|set|list|delete|start|stop|reload]
    permission: wkoth.admin

permissions:
  wkoth.admin:
    description: Permite usar todos los comandos del plugin
    default: op